python plot.py result_datas/slim_demo1.json
python plot.py result_datas/slim_demo1_400k_triangles.json
python plot.py result_datas/slim_demo2.json
python plot.py result_datas/slim_demo3.json
python plot.py result_datas/cot_smoothing_armadillo.json
python plot.py result_datas/cot_smoothing_armadillo_170k_triangles.json
python plot.py result_datas/cot_smoothing_cow.json
python plot.py result_datas/cot_smoothing_10k_surface_37385.json
python plot.py result_datas/optical_flow_small_example.json
python plot.py result_datas/optical_flow_large_example.json
python plot.py result_datas/cot_matrix_armadillo.json
python plot.py result_datas/cot_matrix_armadillo_170k.json
python plot.py result_datas/cot_matrix_37385_sf.json